#nullable enable
using UnityEditor;
using UnityEngine;

namespace GPUGrass.Editor
{
    /// <summary>
    /// Read-only inspector for <see cref="GpuGrassBakeData"/>. The placement arrays (positions / yaws /
    /// scales) are produced by the bake (Tools ▸ GPUGrass ▸ Scene Grass Setup) and must NOT be hand-edited —
    /// editing them would desync the field from its terrain (and the arrays can be huge, so drawing the
    /// default inspector is also slow). This inspector hides the raw arrays entirely and shows a disabled
    /// summary; re-bake to change the data.
    /// </summary>
    [CustomEditor(typeof(GpuGrassBakeData))]
    internal sealed class GpuGrassBakeDataEditor : UnityEditor.Editor
    {
        public override void OnInspectorGUI()
        {
            var bake = (GpuGrassBakeData)this.target;

            EditorGUILayout.HelpBox(
                "Baked GPUGrass placement — generated by Tools ▸ GPUGrass ▸ Scene Grass Setup. " +
                "Read-only; re-bake to change it (do not edit by hand).",
                MessageType.Info);

            // Everything below is non-interactive: the data is managed, not user-authored.
            using (new EditorGUI.DisabledScope(true))
            {
                EditorGUILayout.IntField("Blade Count", bake.InstanceCount);

                Bounds b = bake.WorldBounds;
                EditorGUILayout.Vector3Field("Bounds Center", b.center);
                EditorGUILayout.Vector3Field("Bounds Size", b.size);

                string source = bake.SourceDetailLayer switch
                {
                    -2 => "Terrain surface mesh",
                    -1 => "Detail layers (combined)",
                    < 0 => "Unset",
                    _  => $"Detail layer #{bake.SourceDetailLayer}",
                };
                EditorGUILayout.TextField("Source", source);
            }
        }
    }
}
